apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: telegram-bot
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1000m"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/telegram-bot:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-bot-secrets
              key: token
        - name: WEBHOOK_URL
          value: "https://YOUR_CLOUD_RUN_URL"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
